config/routes.rb
Rails.application.routes.draw do
  resources :kittens

  root to: redirect('/kittens')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kitten_path(@kitten), notice: "Kitten created"
    else
      flash.now[:alert] = "Kitten could not be created"
      render new
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end
  
  def edit
    @kitten = Kitten.find(params[:id])
  end
  
  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to kitten_path(@kitten), notice: "Kitten updated"
    else
      flash.now[:alert] = "Kitten could not be updated"
      render edit
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    redirect_to kittens_path, notice: "Kitten destroyed"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<%= form_with model: @kitten do |f| %>
  <%= f.label :name, 'Nombre' %>
  <%= f.text_field :name %>
  <%= f.label :age, 'Edad' %>
  <%= f.number_field :age %>
  <%= f.label :cuteness, 'Ternura' %>
  <%= f.number_field :cuteness %>
  <%= f.label :softness, 'Suavidad' %>
  <%= f.number_field :softness %>
  <%= f.submit 'Guardar' %>
<% end %>

app/views/kittens/edit.html.erb
<%= render "kitten" %>
<%= link_to "Destroy #{@kitten.name}", @kitten, method: :delete, data: { confirm: "Are you sure you want to kill #{@kitten.name}?" } %>

app/views/kittens/index.html.erb
<h1>Kittens!!</h1>
<% @kittens.each do |kitten| %>
  <h4><%= kitten.name %></h4>
  <ul>
    <li>Age: <%= kitten.age %></li>
    <li>Cuteness: <%= kitten.cuteness %></li>
    <li>Softness: <%= kitten.softness %></li>
  </ul>
  <%= link_to "Destroy #{kitten.name}", kitten, method: "delete", data: { confirm: "Are you sure you want to kill #{kitten.name}?" } %>
<% end %>
<%= link_to "Create a new Kitten!", new_kitten_path %>

app/views/kittens/new.html.erb
<%= render "kitten" %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<ul>
  <li>Age: <%= @kitten.age %></li>
  <li>Cuteness: <%= @kitten.cuteness %></li>
  <li>Softness: <%= @kitten.softness %></li>
</ul>
<%= link_to "Destroy #{@kitten.name}", @kitten, method: :delete, data: { confirm: "Are you sure you want to kill #{@kitten.name}?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>